# Generated by Django 4.0.1 on 2023-10-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointmenttime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available', models.BooleanField(default=True)),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversea_recruitment.service_company')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversea_recruitment.appointmenttime')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oversea_recruitment.service_company')),
            ],
        ),
    ]
