# Generated by Django 4.0.1 on 2023-10-14 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oversea_recruitment', '0003_service_company_subservice_service_company_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_company',
            name='Subservice',
        ),
        migrations.RemoveField(
            model_name='service_company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='service_company',
            name='region',
        ),
        migrations.AddField(
            model_name='service_company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subservice',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='service_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oversea_recruitment.service_company'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
