# Generated by Django 4.0.1 on 2023-10-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oversea_recruitment', '0007_service_company_aboutcompany_service_company_aboutme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_company',
            name='primarycontactcontact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_company',
            name='website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
