# Generated by Django 4.0.1 on 2023-10-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oversea_recruitment', '0008_service_company_primarycontactcontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='servicedetails',
            field=models.FileField(blank=True, null=True, upload_to='servicedetails/'),
        ),
    ]
