# Generated by Django 4.0.1 on 2023-10-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oversea_recruitment', '0009_subservice_cv_subservice_servicedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subservice',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
