# Generated by Django 4.0.1 on 2023-10-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicename', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Service',
        ),
    ]
